#!/usr/bin/env node
// Copies repo-owned data into the Workers packages so they can be bundled without
// reading the filesystem at runtime. Run `node scripts/sync-data.mjs` after editing
// data/agencies/*.json, jurisdictions/*/package.json, workers/schema/d1.sql or
// campaign_tool/assets/styles.css.tmpl. `--check` exits 1 when anything is stale.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const workers = resolve(here, "..");
const repo = resolve(workers, "..");
const check = process.argv.includes("--check");

const banner = "// GENERATED by workers/scripts/sync-data.mjs from ";
const outputs = [];

function planFile(target, content) {
  outputs.push({ target, content });
}

// 1. Agency seeds and law packages -> wizard/src/generated/
const seedDir = join(repo, "data", "agencies");
for (const name of readdirSync(seedDir).filter((f) => f.endsWith(".json")).sort()) {
  planFile(join(workers, "wizard", "src", "generated", "agencies-" + name), readFileSync(join(seedDir, name), "utf8"));
}
const lawDir = join(repo, "jurisdictions");
for (const name of readdirSync(lawDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort()) {
  const pkg = join(lawDir, name, "package.json");
  if (existsSync(pkg)) planFile(join(workers, "wizard", "src", "generated", "law-" + name + ".json"), readFileSync(pkg, "utf8"));
}

// 2. D1 schema -> shared TS constant and workspace migration 0001.
const schemaSql = readFileSync(join(repo, "workers", "schema", "d1.sql"), "utf8");
planFile(join(workers, "workspace", "migrations", "0001_init.sql"), schemaSql);
planFile(
  join(workers, "shared", "src", "generated", "schema.ts"),
  banner + "workers/schema/d1.sql. Do not edit.\nexport const D1_SCHEMA_SQL: string = " + JSON.stringify(schemaSql) + ";\n",
);

// 3. Site CSS -> shared TS constant (placeholders resolved at render time).
const css = readFileSync(join(repo, "campaign_tool", "assets", "styles.css.tmpl"), "utf8");
planFile(
  join(workers, "shared", "src", "generated", "styles.ts"),
  banner + "campaign_tool/assets/styles.css.tmpl. Do not edit.\nexport const STYLES_CSS_TEMPLATE: string = " + JSON.stringify(css) + ";\n",
);

let stale = 0;
for (const { target, content } of outputs) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === content) continue;
  stale += 1;
  if (check) {
    console.error("stale: " + target);
  } else {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
    console.log("wrote " + target);
  }
}
if (check) {
  if (stale) {
    console.error(stale + " generated file(s) out of sync; run `npm run sync` in workers/.");
    process.exit(1);
  }
  console.log("sync-check: " + outputs.length + " generated files match their sources.");
} else if (!stale) {
  console.log("sync: " + outputs.length + " generated files already current.");
}
